"""Per-continent physical, climate and ecology profiles.

For each of the four major continents (named via continents.yaml) this rolls up,
from the per-cell export: Köppen-band composition (A/B/C/D/E), mean ice-corrected
Miami NPP, mountainous fraction and mean elevation. Continent membership uses the
shared connected-landmass assignment in lib/continents (so it agrees exactly with
the biogeography, 97); the reported area is the inventory's canonical continent
area (so it agrees with INVENTORY.md / GEOLOGICAL_HISTORY.md).

Inputs : the 13 csv.gz parts, reports/tectonics/{cache/rasters.npz, inventory.json}
Outputs: reports/tectonics/continent_profiles.json, docs/CONTINENTS.md
"""
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from lib import continents, data_io

# Köppen class id (1..30) -> band letter; 0 = ocean (excluded). See docs/DATA_DICTIONARY.md
BANDS = {**{i: "A" for i in (1, 2, 3)}, **{i: "B" for i in (4, 5, 6, 7)},
         **{i: "C" for i in range(8, 17)}, **{i: "D" for i in range(17, 29)},
         **{i: "E" for i in (29, 30)}}


def temp_c(t):
    return -45.0 + np.clip(t, 0, 1) * 90.0


def miami_npp(koppen, tS, tW, pS, pW):
    """Ice-corrected Miami NPP (g/m²/yr); Köppen-EF (30) ice caps = 0.
    Matches the canonical miamiNpp in tools/regional-report/classify.mjs."""
    T = (temp_c(tS) + temp_c(tW)) / 2.0
    P = (np.maximum(0, pS) + np.maximum(0, pW)) * 1000.0
    npp = np.minimum(3000.0 / (1.0 + np.exp(1.315 - 0.119 * T)),
                     3000.0 * (1.0 - np.exp(-0.000664 * P)))
    return np.where(koppen == 30, 0.0, npp)


inv = data_io.load_inventory()
cols = data_io.load_columns(["lat", "lon", "koppen", "tS", "tW", "pS", "pW",
                             "isMountain", "elev_km", "isLand"])
land = np.flatnonzero(cols["isLand"] == 1)
sel = {k: v[land] for k, v in cols.items()}
koppen = sel["koppen"].astype(int)
npp = miami_npp(koppen, sel["tS"], sel["tW"], sel["pS"], sel["pW"])
cont_names, _ = continents.assign(sel["lat"], sel["lon"])
total_land = len(land)

profiles = {}
for key, c in inv["continents"].items():
    name = c.get("name", key)
    m = cont_names == name
    n = int(m.sum())
    if n == 0:
        continue
    kvals = koppen[m]
    bands = {b: 0 for b in "ABCDE"}
    for k in np.unique(kvals):
        b = BANDS.get(int(k))
        if b:
            bands[b] += int((kvals == k).sum())
    profiles[name] = {
        "key": key,
        "cratons": c["cratons"],
        "centroid": c["centroid"],
        "land_cells": n,
        "pct_land": round(100.0 * n / total_land, 1),
        "area_Mkm2": c["area_Mkm2"],          # canonical (inventory) continent area
        "koppen_band_pct": {b: round(100.0 * bands[b] / n, 1) for b in "ABCDE"},
        "mean_npp_g_m2_yr": round(float(npp[m].mean()), 0),
        "mountainous_pct": round(100.0 * float(sel["isMountain"][m].mean()), 1),
        "mean_elev_km": round(float(sel["elev_km"][m].mean()), 2),
    }

with open(data_io.OUT_DIR / "continent_profiles.json", "w") as f:
    json.dump({"npp": "ice-corrected Miami (Köppen-EF = 0)", "continents": profiles}, f, indent=1)

# ---- docs/CONTINENTS.md ----
order = sorted(profiles.items(), key=lambda kv: -kv[1]["area_Mkm2"])
lines = ["# Continents", "",
         "The four major landmasses of Orogen planet "
         f"`{data_io.load_meta()['planetCode']}`, named in "
         "`tools/tectonics-pipeline/continents.yaml`. Continent membership is the "
         "shared connected-landmass assignment (`lib/continents.py`, also used by the "
         "biogeography); areas are the inventory's canonical continent areas. Köppen "
         "bands (`docs/DATA_DICTIONARY.md`) and ice-corrected Miami NPP "
         "(Köppen-EF = 0) are rolled up per continent.", "",
         "| continent | cratons | area (Mkm²) | % land | A | B | C | D | E | mean NPP (g/m²/yr) | mountainous % | mean elev (km) |",
         "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|"]
for name, p in order:
    b = p["koppen_band_pct"]
    lines.append(f"| **{name}** | {','.join(p['cratons'])} | {p['area_Mkm2']} | {p['pct_land']} | "
                 f"{b['A']} | {b['B']} | {b['C']} | {b['D']} | {b['E']} | "
                 f"{p['mean_npp_g_m2_yr']:.0f} | {p['mountainous_pct']} | {p['mean_elev_km']} |")
lines += ["", "See [`REGION_CROSSWALK.md`](REGION_CROSSWALK.md) for which regional "
          "gazetteers cover each continent (and by how much), and "
          "[`BIOGEOGRAPHY.md`](BIOGEOGRAPHY.md) for per-continent habitat provinces.",
          "", "Köppen bands: **A** tropical · **B** arid · **C** temperate · "
          "**D** continental · **E** polar (percent of each continent's land cells). "
          "Generated by `tools/tectonics-pipeline/scripts/95_continent_profiles.py`.", ""]
(data_io.REPO_ROOT / "docs" / "CONTINENTS.md").write_text("\n".join(lines) + "\n")

print("continent profiles:")
for name, p in order:
    b = p["koppen_band_pct"]
    print(f"  {name:8} {p['area_Mkm2']:>6} Mkm² ({p['pct_land']:.1f}% land)  "
          f"A{b['A']:.0f} B{b['B']:.0f} C{b['C']:.0f} D{b['D']:.0f} E{b['E']:.0f}  "
          f"NPP {p['mean_npp_g_m2_yr']:.0f}")
