#!/usr/bin/env python3
"""Generate docs/DATA_DICTIONARY_V3.md from the v3 extract's orogen_meta.json.

The browser exporter writes a self-describing `fields` block (name, dtype, units,
source, semantics, precision) alongside the data. Rather than hand-maintain an
82-column table that would drift the moment the extract is re-run, this renders
the dictionary straight from that metadata.

    python3 scripts/make_data_dictionary.py

Re-run it after any fresh extract; the doc is a build artefact of the metadata.
"""
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
META = REPO_ROOT / "data" / "orogen_regions_v3_browser" / "orogen_meta.json"
DOC = REPO_ROOT / "docs" / "DATA_DICTIONARY_V3.md"

# Column groupings, in emission order. Any column not listed falls into "Other".
GROUPS = [
    ("Identity & geometry",
     ["id", "lat", "lon", "x", "y", "z", "isSyntheticPole", "cellArea_km2",
      "eastX", "eastY", "eastZ", "northX", "northY", "northZ"]),
    ("Elevation",
     ["elev", "elev_km", "prePost", "postProcessDelta", "erosionDelta"]),
    ("Masks & classification",
     ["isLand", "isMountain", "isTectCoastal", "isSurfaceCoast", "isOceanRegion"]),
    ("Plates & tectonics",
     ["plate", "isOcPlate", "origIsOcPlate", "superPlate", "stress", "tecActivity",
      "tectonic", "orogenicPower", "margins", "backArc", "foldRidge"]),
    ("Terrain component layers",
     ["base", "basin", "coastal", "interior", "noise", "ocean", "hotspot",
      "continentality"]),
    ("Climate — temperature",
     ["tS", "tW", "tempC_S", "tempC_W", "tS_sat", "tW_sat"]),
    ("Climate — precipitation",
     ["pS", "pW", "precipMM_S", "precipMM_W", "pS_p95units", "pW_p95units",
      "pS_censored", "pW_censored", "precip_invertible", "rainShadowSummer",
      "rainShadowWinter"]),
    ("Climate — Köppen",
     ["koppen", "koppen_code"]),
    ("Wind & pressure",
     ["windS_E", "windS_N", "windS_Speed_raw", "windW_E", "windW_N",
      "windW_Speed_raw", "windSpeedSummer", "windSpeedWinter",
      "pressureSummer", "pressureWinter"]),
    ("Ocean currents",
     ["ocS_E", "ocS_N", "ocS_Speed_raw", "ocW_E", "ocW_N", "ocW_Speed_raw",
      "ocSpeedS_norm", "ocSpeedW_norm", "owS", "owW"]),
]


def esc(s):
    """Make a value safe inside a markdown table cell."""
    if s is None:
        return "—"
    return str(s).replace("|", "\\|").replace("\n", " ")


def main():
    if not META.exists():
        print(f"ERROR: no metadata at {META}", file=sys.stderr)
        print("       run the browser extractor first, or place orogen_meta.json there.",
              file=sys.stderr)
        return 1

    m = json.loads(META.read_text(encoding="utf-8"))
    fields = {f["name"]: f for f in m.get("fields", [])}
    cols = m.get("columns", [])
    if not fields or not cols:
        print("ERROR: metadata has no columns/fields block", file=sys.stderr)
        return 1

    L = []
    A = L.append

    A(f"# Data dictionary — v3 browser extract ({len(cols)} columns)")
    A("")
    A(f"Planet [`{m.get('planetCode')}`]({m.get('url')}) · seed `{m.get('seed')}` · "
      f"**{m.get('numRegions', 0):,}** regions · extracted {str(m.get('extractedAt'))[:10]}.")
    A("")
    A("This dataset was captured **live from the running generator** by pasting")
    A("`tools/orogen-extract.js` into the browser console, not produced by the site's")
    A("own CSV export. It therefore carries fields the v1/v2 exports cannot represent —")
    A("most importantly the **uncensored** wind and ocean-current magnitudes.")
    A("")
    A("> Generated by `scripts/make_data_dictionary.py` from")
    A("> `data/orogen_regions_v3_browser/orogen_meta.json`. Do not edit by hand —")
    A("> re-run the script after a fresh extract.")
    A("")

    # ---- how it differs from v1/v2 -------------------------------------
    A("## How v3 differs from v1 / v2")
    A("")
    A("| | v1 | v2 | v3 |")
    A("|---|---|---|---|")
    A("| Columns | 56 | 58 | " + str(len(cols)) + " |")
    A("| Origin | site CSV export | v1 + deterministic correction | live browser capture |")
    A("| Wind / current speed | p95-clamped | p95-clamped | **raw magnitude recovered** |")
    A("| True coastline | ✗ (`isCoastal` is tectonic) | ✓ `isSurfaceCoast` | ✓ `isSurfaceCoast` |")
    A("| Per-cell area | ✗ | ✗ | ✓ `cellArea_km2` |")
    A("| Local E/N basis | ✗ | ✗ | ✓ (vectors reconstructable in 3-D) |")
    A("")

    # ---- the columns ---------------------------------------------------
    A("## Columns")
    A("")
    seen = set()
    for title, names in GROUPS:
        present = [n for n in names if n in fields]
        if not present:
            continue
        seen.update(present)
        A(f"### {title}")
        A("")
        A("| Column | Type | Units | Meaning |")
        A("|---|---|---|---|")
        for n in present:
            f = fields[n]
            A(f"| `{n}` | {esc(f.get('dtype'))} | {esc(f.get('units'))} | "
              f"{esc(f.get('semantics') or f.get('source'))} |")
        A("")

    rest = [c for c in cols if c not in seen and c in fields]
    if rest:
        A("### Other")
        A("")
        A("| Column | Type | Units | Meaning |")
        A("|---|---|---|---|")
        for n in rest:
            f = fields[n]
            A(f"| `{n}` | {esc(f.get('dtype'))} | {esc(f.get('units'))} | "
              f"{esc(f.get('semantics') or f.get('source'))} |")
        A("")

    # ---- conversions ---------------------------------------------------
    conv = m.get("conversions") or {}
    if conv:
        A("## Conversions")
        A("")
        A("| Quantity | Formula |")
        A("|---|---|")
        for k, v in conv.items():
            A(f"| `{k}` | {esc(v)} |")
        A("")

    # ---- recovered p95 -------------------------------------------------
    p95 = m.get("p95") or {}
    solved = {k: v for k, v in p95.items() if isinstance(v, dict) and v.get("p95")}
    if solved:
        A("## Recovered p95 scale factors")
        A("")
        A("The app stores speeds as `min(1, hypot(E,N) / p95)`. Because v3 also carries")
        A("the raw components, the p95 divisor itself can be solved on uncensored cells —")
        A("which means the **normalised speed columns in any export can be returned to raw")
        A("units** by multiplying. `spread` is the solve's residual: small means sound.")
        A("")
        A("| Field | p95 | samples | spread |")
        A("|---|---:|---:|---:|")
        for k, v in solved.items():
            A(f"| {k} | {v['p95']:.6g} | {v.get('samples', '—')} | {v.get('spread', 0):.2g} |")
        A("")

    # ---- caveats -------------------------------------------------------
    notes = m.get("notes") or []
    if notes:
        A("## Caveats you must read before analysis")
        A("")
        for n in notes:
            A(f"- {n}")
        A("")

    # ---- what is absent ------------------------------------------------
    absent = m.get("debugLayersAbsent") or []
    missing = m.get("fieldsMissing") or []
    if absent or missing:
        A("## Not captured in this extract")
        A("")
        if absent:
            A("Debug layers absent (" + str(len(absent)) + "): "
              + ", ".join(f"`{a}`" for a in absent) + ".")
            A("")
        A("Three distinct causes, do not conflate them:")
        A("")
        A("1. **The live site runs an older build.** Nine layers (`cratonWeight`,")
        A("   `basinWeight`, `skeleton`, `noiseAmp`, `foldBeltWeight`, `lip`,")
        A("   `uniformNoise`, `dynamicTopo`, `phasorRidge`) exist only upstream. This")
        A("   extract captured `foldRidge`, the name that layer had *before* it was")
        A("   renamed `phasorRidge` — which is what pins the deployed build as the older")
        A("   one. Nothing client-side can recover these.")
        A("2. **A plate edit destroyed the plate-physics layers.** `plateSpeed`,")
        A("   `continentalDrag`, `sizeVelocity`, `velChange` and `mantleFlow` were wiped")
        A("   because `editDone` replaces `curData.debugLayers` wholesale"
          + (" (`plateEditDetected: true` in this extract)." if m.get("plateEditDetected") else "."))
        A("   **Recoverable:** reload the planet from its code and export *before*")
        A("   touching any plate.")
        A("3. **`tempContinentality` is unreachable on large meshes by design.** It is")
        A("   assigned only in the generation path's non-`skipClimate` branch, and this")
        A("   planet is above `AUTO_CLIMATE_THRESHOLD`, so climate runs through the")
        A("   on-demand path — whose layer set omits it. Recoverable via")
        A("   `CFG.RERUN_WIND` + `CFG.RERUN_TEMP`.")
        A("")
        if missing:
            A("Fields reported missing by the exporter:")
            A("")
            for x in missing:
                A(f"- {x}")
            A("")

    # ---- provenance ----------------------------------------------------
    A("## Provenance")
    A("")
    gp = m.get("generationParams") or {}
    A(f"- Planet code `{m.get('planetCode')}` · seed `{m.get('seed')}` · nMag `{m.get('nMag')}`")
    if gp:
        A(f"- Generation parameters: " + ", ".join(f"`{k}={v}`" for k, v in gp.items()
                                                   if k not in ("toggledIndices",)))
    A(f"- Climate computed: {m.get('climateComputed')} · super-plates: {m.get('superPlateCount')}")
    A(f"- Parts: {len(m.get('parts', []))} × `.csv.gz`, {m.get('rowsPerPart'):,} rows each")
    dm = m.get("dualMesh") or {}
    if dm:
        A(f"- Dual mesh: {dm.get('numTriangles', 0):,} triangles, "
          f"{dm.get('numRegions', 0):,} regions — {', '.join(dm.get('files', []))}")
    A(f"- Extraction took {m.get('elapsedSeconds')} s")
    A("")
    A("Sidecars: `orogen_plates.csv` (per-plate table; join on `plate`), "
      "`orogen_koppen_classes.csv` (the `koppen` ↔ `koppen_code` table), "
      "`orogen_itcz.csv` (ITCZ curves).")
    A("")
    A("Integrity: generate a manifest with `python3 scripts/make_manifest.py --v3`, "
      "then check it any time with `python3 scripts/verify_parts.py --v3`.")
    A("")

    DOC.parent.mkdir(parents=True, exist_ok=True)
    DOC.write_text("\n".join(L), encoding="utf-8")
    print(f"Wrote {DOC}")
    print(f"  {len(cols)} columns documented across {len(GROUPS)} groups"
          + (f", {len(rest)} ungrouped" if rest else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
